-- =============================================================================
-- Migración 135: Corrección de Catálogos e Integridad de Roles
--   1. Inserta el catálogo completo de países ISO 3166-1 (y actualiza existentes).
--   2. Actualiza abreviatura e iso_3166_2 para todos los 32 estados de México.
--   3. Asegura columnas de auditoría en ades_usuario_roles y puebla con rol_id actual.
-- =============================================================================
BEGIN;

-- 1. POBLAR / ACTUALIZAR CATÁLOGO COMPLETO DE PAÍSES (200+ países con datos completos e ISO)
INSERT INTO public.ades_paises (
  clave_pais, nombre_pais, iso_alpha_3, iso_numeric, nombre_en, nombre_fr, nombre_oficial_es, codigo_telefono, region, emoji_bandera, nacionalidad
)
VALUES
  ('AD','Andorra','AND','020','Andorra','Andorre','Principado de Andorra','+376','Europa','🇦🇩','Andorrana'),
  ('AE','Emiratos Árabes Unidos','ARE','784','United Arab Emirates','Émirats arabes unis','Emiratos Árabes Unidos','+971','Oriente Medio','🇦🇪','Emiratí'),
  ('AF','Afganistán','AFG','004','Afghanistan','Afghanistan','República Islámica de Afganistán','+93','Asia Central','🇦🇫','Afgana'),
  ('AG','Antigua y Barbuda','ATG','028','Antigua and Barbuda','Antigua-et-Barbuda','Antigua y Barbuda','+1-268','El Caribe','🇦🇬','Antiguense'),
  ('AI','Anguilla','AIA','660','Anguilla','Anguilla','Anguilla','+1-264','El Caribe','🇦🇮','Anguileña'),
  ('AL','Albania','ALB','008','Albania','Albanie','República de Albania','+355','Europa','🇦🇱','Albanesa'),
  ('AM','Armenia','ARM','051','Armenia','Arménie','República de Armenia','+374','Asia Occidental','🇦🇲','Armenia'),
  ('AO','Angola','AGO','024','Angola','Angola','República de Angola','+244','África','🇦🇴','Angoleña'),
  ('AQ','Antártida','AQD','010','Antarctica','Antarctique','Antártida',NULL,'Antártida y Territorios','🇦🇶',NULL),
  ('AR','Argentina','ARG','032','Argentina','Argentine','República Argentina','+54','América del Sur','🇦🇷','Argentina'),
  ('AS','Samoa Americana','ASM','016','American Samoa','Samoa américaines','Samoa Americana','+1-684','Oceanía','🇦🇸','Samoana Americana'),
  ('AT','Austria','AUT','040','Austria','Autriche','República de Austria','+43','Europa','🇦🇹','Austriaca'),
  ('AU','Australia','AUS','036','Australia','Australie','Commonwealth de Australia','+61','Oceanía','🇦🇺','Australiana'),
  ('AW','Aruba','AWB','533','Aruba','Aruba','Aruba','+297','El Caribe','🇦🇼','Arubense'),
  ('AX','Islas Åland','ALA','248','Åland Islands','Îles Åland','Islas Åland','+358','Europa','🇦🇽','Alandesa'),
  ('AZ','Azerbaiyán','AZE','031','Azerbaijan','Azerbaïdjan','República de Azerbaiyán','+994','Asia Occidental','🇦🇿','Azerbaiyana'),
  ('BA','Bosnia y Herzegovina','BIH','070','Bosnia and Herzegovina','Bosnie-Herzégovine','Bosnia y Herzegovina','+387','Europa','🇧🇦','Bosnia'),
  ('BB','Barbados','BRB','052','Barbados','Barbade','Barbados','+1-246','El Caribe','🇧🇧','Barbadense'),
  ('BD','Bangladesh','BGD','050','Bangladesh','Bangladesh','República Popular de Bangladesh','+880','Asia Meridional','🇧🇩','Bangladesí'),
  ('BE','Bélgica','BEL','056','Belgium','Belgique','Reino de Bélgica','+32','Europa','🇧🇪','Belga'),
  ('BF','Burkina Faso','BFA','854','Burkina Faso','Burkina Faso','Burkina Faso','+226','África','🇧🇫','Burkinabé'),
  ('BG','Bulgaria','BGR','100','Bulgaria','Bulgarie','República de Bulgaria','+359','Europa','🇧🇬','Búlgara'),
  ('BH','Baréin','BHR','048','Bahrain','Bahreïn','Reino de Baréin','+973','Oriente Medio','🇧🇭','Bareiní'),
  ('BI','Burundi','BDI','108','Burundi','Burundi','República de Burundi','+257','África','🇧🇮','Burundesa'),
  ('BJ','Benín','BEN','204','Benin','Bénin','República de Benín','+229','África','🇧🇯','Beninesa'),
  ('BL','San Bartolomé','BLM','652','Saint Barthélemy','Saint-Barthélemy','San Bartolomé','+590','El Caribe','🇧🇱','Sanbartolemesa'),
  ('BM','Bermudas','BMU','060','Bermuda','Bermudes','Bermudas','+1-441','América del Norte','🇧🇲','Bermudense'),
  ('BN','Brunéi','BRN','096','Brunei','Brunéi Darussalam','Brunéi Darussalam','+673','Asia Sudoriental','🇧🇳','Bruneyana'),
  ('BO','Bolivia','BOL','068','Bolivia','Bolivie','Estado Plurinacional de Bolivia','+591','América del Sur','🇧🇴','Boliviana'),
  ('BQ','Caribe Neerlandés','BES','535','Caribbean Netherlands','Pays-Bas caribéens','Caribe Neerlandés','+599','El Caribe','🇧🇶','Neerlandesa'),
  ('BR','Brasil','BRA','076','Brazil','Brésil','República Federativa del Brasil','+55','América del Sur','🇧🇷','Brasileña'),
  ('BS','Bahamas','BHS','044','Bahamas','Bahamas','Commonwealth de las Bahamas','+1-242','El Caribe','🇧🇸','Bahamense'),
  ('BT','Bután','BTN','064','Bhutan','Bhoutan','Reino de Bután','+975','Asia Meridional','🇧🇹','Butanesa'),
  ('BV','Isla Bouvet','BVT','074','Bouvet Island','Île Bouvet','Isla Bouvet',NULL,'Antártida y Territorios','🇧🇻',NULL),
  ('BW','Botsuana','BWA','072','Botswana','Botswana','República de Botsuana','+267','África','🇧🇼','Botsuanesa'),
  ('BY','Bielorrusia','BLR','112','Belarus','Bélarus','República de Bielorrusia','+375','Europa','🇧🇾','Bielorrusa'),
  ('BZ','Belice','BLZ','084','Belize','Belize','Belice','+501','América Central','🇧🇿','Beliceña'),
  ('CA','Canadá','CAN','124','Canada','Canada','Canadá','+1','América del Norte','🇨🇦','Canadiense'),
  ('CC','Islas Cocos','CCK','166','Cocos Islands','Îles Cocos','Territorio de las Islas Cocos','+61','Oceanía','🇨🇨',NULL),
  ('CD','República Democrática del Congo','COD','180','DR Congo','Congo (Rép. dém.)','República Democrática del Congo','+243','África','🇨🇩','Congoleña'),
  ('CF','República Centroafricana','CAF','140','Central African Republic','République centrafricaine','República Centroafricana','+236','África','🇨🇫','Centroafricana'),
  ('CG','República del Congo','COG','178','Republic of the Congo','République du Congo','República del Congo','+242','África','🇨🇬','Congoleña'),
  ('CH','Suiza','CHE','756','Switzerland','Suisse','Confederación Suiza','+41','Europa','🇨🇭','Suiza'),
  ('CI','Costa de Marfil','CIV','384','Ivory Coast','Côte d''Ivoire','República de Côte d''Ivoire','+225','África','🇨🇮','Marfileña'),
  ('CK','Islas Cook','COK','184','Cook Islands','Îles Cook','Islas Cook','+682','Oceanía','🇨🇰',NULL),
  ('CL','Chile','CHL','152','Chile','Chili','República de Chile','+56','América del Sur','🇨🇱','Chilena'),
  ('CM','Camerún','CMR','120','Cameroon','Cameroun','República de Camerún','+237','África','🇨🇲','Camerunesa'),
  ('CN','China','CHN','156','China','Chine','República Popular China','+86','Asia Oriental','🇨🇳','China'),
  ('CO','Colombia','COL','170','Colombia','Colombie','República de Colombia','+57','América del Sur','🇨🇴','Colombiana'),
  ('CR','Costa Rica','CRI','188','Costa Rica','Costa Rica','República de Costa Rica','+506','América Central','🇨🇷','Costarricense'),
  ('CU','Cuba','CUB','192','Cuba','Cuba','República de Cuba','+53','El Caribe','🇨🇺','Cubana'),
  ('CV','Cabo Verde','CPV','132','Cape Verde','Cabo Verde','República de Cabo Verde','+238','África','🇨🇻','Caboverdiana'),
  ('CW','Curazao','CUW','531','Curaçao','Curaçao','Curazao','+599','El Caribe','🇨🇼','Curazoleña'),
  ('CX','Isla de Navidad','CXR','162','Christmas Island','Île Christmas','Isla de Navidad','+61','Oceanía','🇨🇽',NULL),
  ('CY','Chipre','CYP','196','Cyprus','Chypre','República de Chipre','+357','Europa','🇨🇾','Chipriota'),
  ('CZ','República Checa','CZE','203','Czech Republic','Tchéquie','República Checa','+420','Europa','🇨🇿','Checa'),
  ('DE','Alemania','DEU','276','Germany','Allemagne','República Federal de Alemania','+49','Europa','🇩🇪','Alemana'),
  ('DJ','Yibuti','DJI','262','Djibouti','Djibouti','República de Yibuti','+253','África','🇩🇯','Yibutiana'),
  ('DK','Dinamarca','DNK','208','Denmark','Danemark','Reino de Dinamarca','+45','Europa','🇩🇰','Danesa'),
  ('DM','Dominica','DMA','212','Dominica','Dominique','Commonwealth de Dominica','+1-767','El Caribe','🇩🇲','Dominiquesa'),
  ('DO','República Dominicana','DOM','214','Dominican Republic','République dominicaine','República Dominicana','+1-809','El Caribe','🇩🇴','Dominicana'),
  ('DZ','Argelia','DZA','012','Algeria','Algérie','República Argelina Democrática y Popular','+213','África','🇩🇿','Argelina'),
  ('EC','Ecuador','ECU','218','Ecuador','Équateur','República del Ecuador','+593','América del Sur','🇪🇨','Ecuatoriana'),
  ('EE','Estonia','EST','233','Estonia','Estonie','República de Estonia','+372','Europa','🇪🇪','Estonia'),
  ('EG','Egipto','EGY','818','Egypt','Égypte','República Árabe de Egipto','+20','África','🇪🇬','Egipcia'),
  ('EH','Sahara Occidental','ESH','732','Western Sahara','Sahara occidental','Sahara Occidental','+212','África','🇪🇭','Saharaui'),
  ('ER','Eritrea','ERI','232','Eritrea','Érythrée','Estado de Eritrea','+291','África','🇪🇷','Eritrea'),
  ('ES','España','ESP','724','Spain','Espagne','Reino de España','+34','Europa','🇪🇸','Española'),
  ('ET','Etiopía','ETH','231','Ethiopia','Éthiopie','República Democrática Federal de Etiopía','+251','África','🇪🇹','Etíope'),
  ('FI','Finlandia','FIN','246','Finland','Finlande','República de Finlandia','+358','Europa','🇫🇮','Finlandesa'),
  ('FJ','Fiyi','FJI','242','Fiji','Fidji','República de Fiyi','+679','Oceanía','🇫🇯','Fiyiana'),
  ('FK','Islas Malvinas','FLK','238','Falkland Islands','Îles Malouines','Islas Malvinas','+500','América del Sur','🇫🇰',NULL),
  ('FM','Micronesia','FSM','583','Micronesia','Micronésie','Estados Federados de Micronesia','+691','Oceanía','🇫🇲','Micronesia'),
  ('FO','Islas Feroe','FRO','234','Faroe Islands','Îles Féroé','Islas Feroe','+298','Europa','🇫🇴','Feroesa'),
  ('FR','Francia','FRA','250','France','France','República Francesa','+33','Europa','🇫🇷','Francesa'),
  ('GA','Gabón','GAB','266','Gabon','Gabon','República Gabonesa','+241','África','🇬🇦','Gabonesa'),
  ('GB','Reino Unido','GBR','826','United Kingdom','Royaume-Uni','Reino Unido de Gran Bretaña e Irlanda del Norte','+44','Europa','🇬🇧','Británica'),
  ('GD','Granada','GRD','308','Grenada','Grenade','Granada','+1-473','El Caribe','🇬🇩','Granadina'),
  ('GE','Georgia','GEO','268','Georgia','Géorgie','Georgia','+995','Asia Occidental','🇬🇪','Georgiana'),
  ('GF','Guayana Francesa','GUF','254','French Guiana','Guyane française','Guayana Francesa','+594','América del Sur','🇬🇫','Guayanesa'),
  ('GG','Guernsey','GGY','831','Guernsey','Guernesey','Guernsey','+44','Europa','🇬🇬','Guernesiana'),
  ('GH','Ghana','GHA','288','Ghana','Ghana','República de Ghana','+233','África','🇬🇭','Ghanesa'),
  ('GI','Gibraltar','GIB','292','Gibraltar','Gibraltar','Gibraltar','+350','Europa','🇬🇮','Gibraltareña'),
  ('GL','Groenlandia','GRL','304','Greenland','Groenland','Groenlandia','+299','América del Norte','🇬🇱','Groenlandesa'),
  ('GM','Gambia','GMB','270','Gambia','Gambie','República de Gambia','+220','África','🇬🇲','Gambiana'),
  ('GN','Guinea','GIN','324','Guinea','Guinée','República de Guinea','+224','África','🇬🇳','Guineana'),
  ('GP','Guadalupe','GLP','312','Guadeloupe','Guadeloupe','Guadalupe','+590','El Caribe','🇬🇵','Guadalupana'),
  ('GQ','Guinea Ecuatorial','GNQ','226','Equatorial Guinea','Guinée équatoriale','República de Guinea Ecuatorial','+240','África','🇬🇶','Ecuatoguineana'),
  ('GR','Grecia','GRC','300','Greece','Grèce','República Helénica','+30','Europa','🇬🇷','Griega'),
  ('GS','Islas Georgias del Sur y Sandwich del Sur','SGS','239','South Georgia','Géorgie du Sud','Islas Georgias del Sur y Sandwich del Sur','+500','Antártida y Territorios','🇬🇸',NULL),
  ('GT','Guatemala','GTM','320','Guatemala','Guatemala','República de Guatemala','+502','América Central','🇬🇹','Guatemalteca'),
  ('GU','Guam','GUM','316','Guam','Guam','Guam','+1-671','Oceanía','🇬🇺','Guameña'),
  ('GW','Guinea-Bisáu','GNB','624','Guinea-Bissau','Guinée-Bissau','República de Guinea-Bisáu','+245','África','🇬🇼','Bisauguineana'),
  ('GY','Guyana','GUY','328','Guyana','Guyana','República Cooperativa de Guyana','+592','América del Sur','🇬🇾','Guyanesa'),
  ('HK','Hong Kong','HKG','344','Hong Kong','Hong Kong','Región Administrativa Especial de Hong Kong','+852','Asia Oriental','🇭🇰','Hongkonesa'),
  ('HM','Islas Heard y McDonald','HMD','334','Heard Island','Île Heard','Islas Heard y McDonald',NULL,'Antártida y Territorios','🇭🇲',NULL),
  ('HN','Honduras','HND','340','Honduras','Honduras','República de Honduras','+504','América Central','🇭🇳','Hondureña'),
  ('HR','Croacia','HRV','191','Croatia','Croatie','República de Croacia','+385','Europa','🇭🇷','Croata'),
  ('HT','Haití','HTI','332','Haiti','Haïti','República de Haití','+509','El Caribe','🇭🇹','Haitiana'),
  ('HU','Hungría','HUN','348','Hungary','Hongrie','Hungría','+36','Europa','🇭🇺','Húngara'),
  ('ID','Indonesia','IDN','360','Indonesia','Indonésie','República de Indonesia','+62','Asia Sudoriental','🇮🇩','Indonesia'),
  ('IE','Irlanda','IRL','372','Ireland','Irlande','Irlanda','+353','Europa','🇮🇪','Irlandesa'),
  ('IL','Israel','ISR','376','Israel','Israël','Estado de Israel','+972','Oriente Medio','🇮🇱','Israelí'),
  ('IM','Isla de Man','IMN','833','Isle of Man','Île de Man','Isla de Man','+44','Europa','🇮🇲','Manesa'),
  ('IN','India','IND','356','India','Inde','República de India','+91','Asia Meridional','🇮🇳','India'),
  ('IO','Territorio Británico del Océano Índico','IOT','086','British Indian Ocean Territory','Territoire britannique de l''océan Indien','Territorio Británico del Océano Índico','+246','Asia Meridional','🇮🇴',NULL),
  ('IQ','Irak','IRQ','368','Iraq','Iraq','República de Irak','+964','Oriente Medio','🇮🇶','Iraquí'),
  ('IR','Irán','IRN','364','Iran','Iran','República Islámica de Irán','+98','Oriente Medio','🇮🇷','Iraní'),
  ('IS','Islandia','ISL','352','Iceland','Islande','Islandia','+354','Europa','🇮🇸','Islandesa'),
  ('IT','Italia','ITA','380','Italy','Italie','República Italiana','+39','Europa','🇮🇹','Italiana'),
  ('JE','Jersey','JEY','832','Jersey','Jersey','Jersey','+44','Europa','🇯🇪','Jersiana'),
  ('JM','Jamaica','JAM','388','Jamaica','Jamaïque','Jamaica','+1-876','El Caribe','🇯🇲','Jamaicana'),
  ('JO','Jordania','JOR','400','Jordan','Jordanie','Reino Hachemita de Jordania','+962','Oriente Medio','🇯🇴','Jordana'),
  ('JP','Japón','JPN','392','Japan','Japon','Japón','+81','Asia Oriental','🇯🇵','Japonesa'),
  ('KE','Kenia','KEN','404','Kenya','Kenya','República de Kenia','+254','África','🇰🇪','Keniana'),
  ('KG','Kirguistán','KGZ','417','Kyrgyzstan','Kirghizistan','República Kirguís','+996','Asia Central','🇰🇬','Kirguisa'),
  ('KH','Camboya','KHM','116','Cambodia','Cambodge','Reino de Camboya','+855','Asia Sudoriental','🇰🇭','Camboyana'),
  ('KI','Kiribati','KIR','296','Kiribati','Kiribati','República de Kiribati','+686','Oceanía','🇰🇮','Kiribatiana'),
  ('KM','Comoras','COM','174','Comoros','Comores','Unión de las Comoras','+269','África','🇰🇲','Comorense'),
  ('KN','San Cristóbal y Nieves','KNA','659','Saint Kitts and Nevis','Saint-Kitts-et-Nevis','Federación de Saint Kitts y Nevis','+1-869','El Caribe','🇰🇳','Sancristobaleña'),
  ('KP','Corea del Norte','PRK','408','North Korea','Corée du Nord','República Popular Democrática de Corea','+850','Asia Oriental','🇰🇵','Norcoreana'),
  ('KR','Corea del Sur','KOR','410','South Korea','Corée du Sud','República de Corea','+82','Asia Oriental','🇰🇷','Surcoreana'),
  ('KW','Kuwait','KWT','414','Kuwait','Koweït','Estado de Kuwait','+965','Oriente Medio','🇰🇼','Kuwaití'),
  ('KY','Islas Caimán','CYM','136','Cayman Islands','Îles Caïmans','Islas Caimán','+1-345','El Caribe','🇰🇾','Caymanesa'),
  ('KZ','Kazajistán','KAZ','398','Kazakhstan','Kazakhstan','República de Kazajistán','+7','Asia Central','🇰🇿','Kazaja'),
  ('LA','Laos','LAO','418','Laos','Laos','República Democrática Popular Lao','+856','Asia Sudoriental','🇱🇦','Laosiana'),
  ('LB','Líbano','LBN','422','Lebanon','Liban','República Libanesa','+961','Oriente Medio','🇱🇧','Libanesa'),
  ('LC','Santa Lucía','LCA','662','Saint Lucia','Sainte-Lucie','Santa Lucía','+1-758','El Caribe','🇱🇨','Santaluciana'),
  ('LI','Liechtenstein','LIE','438','Liechtenstein','Liechtenstein','Principado de Liechtenstein','+423','Europa','🇱🇮','Liechtensteiniana'),
  ('LK','Sri Lanka','LKA','144','Sri Lanka','Sri Lanka','República Democrática Socialista de Sri Lanka','+94','Asia Meridional','🇱🇰','Esrilanquesa'),
  ('LR','Liberia','LBR','430','Liberia','Libéria','República de Liberia','+231','África','🇱🇷','Liberiana'),
  ('LS','Lesoto','LSO','426','Lesotho','Lesotho','Reino de Lesotho','+266','África','🇱🇸','Lesotense'),
  ('LT','Lituania','LTU','440','Lithuania','Lituanie','República de Lituania','+370','Europa','🇱🇹','Lituana'),
  ('LU','Luxemburgo','LUX','442','Luxembourg','Luxembourg','Gran Ducado de Luxemburgo','+352','Europa','🇱🇺','Luxemburguesa'),
  ('LV','Letonia','LVA','428','Latvia','Lettonie','República de Letonia','+371','Europa','🇱🇻','Letona'),
  ('LY','Libia','LBY','434','Libya','Libye','Estado de Libia','+218','África','🇱🇾','Libia'),
  ('MA','Marruecos','MAR','504','Morocco','Maroc','Reino de Marruecos','+212','África','🇲🇦','Marroquí'),
  ('MC','Mónaco','MCO','492','Monaco','Monaco','Principado de Mónaco','+377','Europa','🇲🇨','Monegasca'),
  ('MD','Moldavia','MDA','498','Moldova','Moldavie','República de Moldova','+373','Europa','🇲🇩','Moldava'),
  ('ME','Montenegro','MNE','499','Montenegro','Monténégro','Montenegro','+382','Europa','🇲🇪','Montenegrina'),
  ('MF','San Martín','MAF','663','Saint Martin','Saint-Martin','Colectividad de San Martín','+590','El Caribe','🇲🇫',NULL),
  ('MG','Madagascar','MDG','450','Madagascar','Madagascar','República de Madagascar','+261','África','🇲🇬','Malgache'),
  ('MH','Islas Marshall','MHL','584','Marshall Islands','Îles Marshall','República de las Islas Marshall','+692','Oceanía','🇲🇭','Marshalesa'),
  ('MK','Macedonia del Norte','MKD','807','North Macedonia','Macédoine du Nord','República de Macedonia del Norte','+389','Europa','🇲🇰','Macedónica'),
  ('ML','Malí','MLI','466','Mali','Mali','República de Malí','+223','África','🇲🇱','Maliense'),
  ('MM','Birmania','MMR','104','Myanmar','Myanmar','República de la Unión de Myanmar','+95','Asia Sudoriental','🇲🇲','Birmana'),
  ('MN','Mongolia','MNG','496','Mongolia','Mongolie','Mongolia','+976','Asia Oriental','🇲🇳','Mongola'),
  ('MO','Macao','MAC','446','Macao','Macao','Región Administrativa Especial de Macao','+853','Asia Oriental','🇲🇴','Macaense'),
  ('MP','Islas Marianas del Norte','MNP','580','Northern Mariana Islands','Îles Mariannes du Nord','Islas Marianas del Norte','+1-670','Oceanía','🇲🇵',NULL),
  ('MQ','Martinica','MQT','474','Martinique','Martinique','Martinica','+596','El Caribe','🇲🇶','Martiniqueña'),
  ('MR','Mauritania','MRT','478','Mauritania','Mauritanie','República Islámica de Mauritania','+222','África','🇲🇷','Mauritana'),
  ('MS','Montserrat','MSR','500','Montserrat','Montserrat','Montserrat','+1-664','El Caribe','🇲🇸','Montserratiana'),
  ('MT','Malta','MLT','470','Malta','Malte','República de Malta','+356','Europa','🇲🇹','Maltesa'),
  ('MU','Mauricio','MUS','480','Mauritius','Maurice','República de Mauricio','+230','África','🇲🇺','Mauriciana'),
  ('MV','Maldivas','MDV','462','Maldives','Maldives','República de Maldivas','+960','Asia Meridional','🇲🇻','Maldiva'),
  ('MW','Malaui','MWI','454','Malawi','Malawi','República de Malaui','+265','África','🇲🇼','Malauiana'),
  ('MX','México','MEX','484','Mexico','Mexique','Estados Unidos Mexicanos','+52','América del Norte','🇲🇽','Mexicana'),
  ('MY','Malasia','MYS','458','Malaysia','Malaisie','Malasia','+60','Asia Sudoriental','🇲🇾','Malaya'),
  ('MZ','Mozambique','MOZ','508','Mozambique','Mozambique','República de Mozambique','+258','África','🇲🇿','Mozambiqueña'),
  ('NA','Namibia','NAM','516','Namibia','Namibie','República de Namibia','+264','África','🇳🇦','Namibia'),
  ('NC','Nueva Caledonia','NCL','540','New Caledonia','Nouvelle-Calédonie','Nueva Caledonia','+687','Oceanía','🇳🇨','Neocaledonia'),
  ('NE','Níger','NER','562','Niger','Niger','República del Níger','+227','África','🇳🇪','Nigerina'),
  ('NF','Isla Norfolk','NFK','574','Norfolk Island','Île Norfolk','Isla Norfolk','+672','Oceanía','🇳🇫',NULL),
  ('NG','Nigeria','NGA','566','Nigeria','Nigéria','República Federal de Nigeria','+234','África','🇳🇬','Nigeriana'),
  ('NI','Nicaragua','NIC','558','Nicaragua','Nicaragua','República de Nicaragua','+505','América Central','🇳🇮','Nicaragüense'),
  ('NL','Países Bajos','NLD','528','Netherlands','Pays-Bas','Reino de los Países Bajos','+31','Europa','🇳🇱','Neerlandesa'),
  ('NO','Noruega','NOR','578','Norway','Norvège','Reino de Noruega','+47','Europa','🇳🇴','Noruega'),
  ('NP','Nepal','NPL','524','Nepal','Népal','República Democrática Federal de Nepal','+977','Asia Meridional','🇳🇵','Nepalesa'),
  ('NR','Nauru','NRU','520','Nauru','Nauru','República de Nauru','+674','Oceanía','🇳🇷','Nauruana'),
  ('NU','Niue','NIU','570','Niue','Niue','Niue','+683','Oceanía','🇳🇺','Niueña'),
  ('NZ','Nueva Zelanda','NZL','554','New Zealand','Nouvelle-Zélande','Nueva Zelanda','+64','Oceanía','🇳🇿','Neozelandesa'),
  ('OM','Omán','OMN','512','Oman','Oman','Sultanato de Omán','+968','Oriente Medio','🇴🇲','Omaní'),
  ('PA','Panamá','PAN','591','Panama','Panama','República de Panamá','+507','América Central','🇵🇦','Panameña'),
  ('PE','Perú','PER','604','Peru','Pérou','República del Perú','+51','América del Sur','🇵🇪','Peruana'),
  ('PF','Polinesia Francesa','PYF','258','French Polynesia','Polynésie française','Polinesia Francesa','+689','Oceanía','🇵🇫','Polinesia'),
  ('PG','Papúa Nueva Guinea','PNG','598','Papua New Guinea','Papouasie-Nouvelle-Guinée','Estado Independiente de Papúa Nueva Guinea','+675','Oceanía','🇵🇬','Papú'),
  ('PH','Filipinas','PHL','608','Philippines','Philippines','República de Filipinas','+63','Asia Sudoriental','🇵🇭','Filipina'),
  ('PK','Pakistán','PAK','586','Pakistan','Pakistan','República Islámica de Pakistán','+92','Asia Meridional','🇵🇰','Pakistaní'),
  ('PL','Polonia','POL','616','Poland','Pologne','República de Polonia','+48','Europa','🇵🇱','Polaca'),
  ('PM','San Pedro y Miquelón','SPM','666','Saint Pierre and Miquelon','Saint-Pierre-et-Miquelon','San Pedro y Miquelón','+508','América del Norte','🇵🇲',NULL),
  ('PN','Islas Pitcairn','PCN','612','Pitcairn Islands','Îles Pitcairn','Islas Pitcairn','+64','Oceanía','🇵🇳',NULL),
  ('PR','Puerto Rico','PRI','630','Puerto Rico','Porto Rico','Estado Libre Asociado de Puerto Rico','+1-787','El Caribe','🇵🇷','Puertorriqueña'),
  ('PS','Palestina','PSE','275','Palestine','Territoire palestinien','Estado de Palestina','+970','Oriente Medio','🇵🇸','Palestina'),
  ('PT','Portugal','PRT','620','Portugal','Portugal','República Portuguesa','+351','Europa','🇵🇹','Portuguesa'),
  ('PW','Palaos','PLW','585','Palau','Palaos','República de Palaos','+680','Oceanía','🇵🇼','Palauesa'),
  ('PY','Paraguay','PRY','600','Paraguay','Paraguay','República del Paraguay','+595','América del Sur','🇵🇾','Paraguaya'),
  ('QA','Catar','QAT','634','Qatar','Qatar','Estado de Catar','+974','Oriente Medio','🇶🇦','Catarí'),
  ('RE','Reunión','REU','638','Réunion','La Réunion','Reunión','+262','África','🇷🇪','Reunionesa'),
  ('RO','Rumanía','ROU','642','Romania','Roumanie','República de Rumanía','+40','Europa','🇷🇴','Rumana'),
  ('RS','Serbia','SRB','688','Serbia','Serbie','República de Serbia','+381','Europa','🇷🇸','Serbia'),
  ('RU','Rusia','RUS','643','Russia','Russie','Federación de Rusia','+7','Europa','🇷🇺','Rusa'),
  ('RW','Ruanda','RWA','646','Rwanda','Rwanda','República de Ruanda','+250','África','🇷🇼','Ruandesa'),
  ('SA','Arabia Saudita','SAU','682','Saudi Arabia','Arabie saoudite','Reino de Arabia Saudita','+966','Oriente Medio','🇸🇦','Saudita'),
  ('SB','Islas Salomón','SLB','090','Solomon Islands','Îles Salomon','Islas Salomón','+677','Oceanía','🇸🇧','Salomonense'),
  ('SC','Seychelles','SYC','690','Seychelles','Seychelles','República de Seychelles','+248','África','🇸🇨','Seychellense'),
  ('SD','Sudán','SDN','729','Sudan','Soudan','República del Sudán','+249','África','🇸🇩','Sudanesa'),
  ('SE','Suecia','SWE','752','Sweden','Suède','Reino de Suecia','+46','Europa','🇸🇪','Sueca'),
  ('SG','Singapur','SGP','702','Singapore','Singapour','República de Singapur','+65','Asia Sudoriental','🇸🇬','Singapurense'),
  ('SH','Santa Elena, Ascensión y Tristán de Acuña','SHN','654','Saint Helena','Sainte-Hélène','Santa Elena, Ascensión y Tristán de Acuña','+290','África','🇸🇭',NULL),
  ('SI','Eslovenia','SVN','705','Slovenia','Slovaquie','República de Eslovenia','+386','Europa','🇸🇮','Eslovena'),
  ('SJ','Svalbard y Jan Mayen','SJM','744','Svalbard and Jan Mayen','Svalbard et Jan Mayen','Svalbard y Jan Mayen','+47','Europa','🇸🇯',NULL),
  ('SK','Eslovaquia','SVK','703','Slovakia','Slovaquie','República Eslovaca','+421','Europa','🇸🇰','Eslovaca'),
  ('SL','Sierra Leona','SLE','694','Sierra Leone','Sierra Leone','República de Sierra Leona','+232','África','🇸🇱','Sierraleonesa'),
  ('SM','San Marino','SMR','674','San Marino','Saint-Marin','República de San Marino','+378','Europa','🇸🇲','Sanmarinense'),
  ('SN','Senegal','SEN','686','Senegal','Sénégal','República de Senegal','+221','África','🇸🇳','Senegalesa'),
  ('SO','Somalia','SOM','706','Somalia','Somalie','República Federal de Somalia','+252','África','🇸🇴','Somalí'),
  ('SR','Surinam','SUR','740','Suriname','Suriname','República de Surinam','+597','América del Sur','🇸🇷','Surinamesa'),
  ('SS','Sudán del Sur','SSD','728','South Sudan','Soudan du Sud','República de Sudán del Sur','+211','África','🇸🇸','Sursudanesa'),
  ('ST','Santo Tomé y Príncipe','STP','678','São Tomé and Príncipe','Sao Tomé-et-Principe','República Democrática de Santo Tomé y Príncipe','+239','África','🇸🇹','Santotomense'),
  ('SV','El Salvador','SLV','222','El Salvador','El Salvador','República de El Salvador','+503','América Central','🇸🇻','Salvadoreña'),
  ('SX','Sint Maarten','SXM','534','Sint Maarten','Saint-Martin','Sint Maarten','+1-721','El Caribe','🇸🇽',NULL),
  ('SY','Siria','SYR','760','Syria','Syrie','República Árabe Siria','+963','Oriente Medio','🇸🇾','Siria'),
  ('SZ','Esuatini','SWZ','748','Eswatini','Eswatini','Reino de Esuatini','+268','África','🇸🇿','Suazi'),
  ('TC','Islas Turcas y Caicos','TCA','796','Turks and Caicos Islands','Îles Turks-et-Caïcos','Islas Turcas y Caicos','+1-649','El Caribe','🇹🇨',NULL),
  ('TD','Chad','TCD','148','Chad','Tchad','República del Chad','+235','África','🇹🇩','Chadiana'),
  ('TF','Tierras Australes y Antárticas Francesas','ATF','260','French Southern Territories','Terres australes françaises','Tierras Australes y Antárticas Francesas',NULL,'Antártida y Territorios','🇹🇫',NULL),
  ('TG','Togo','TGO','768','Togo','Togo','República Togolesa','+228','África','🇹🇬','Togolesa'),
  ('TH','Tailandia','THA','764','Thailand','Thaïlande','Reino de Tailandia','+66','Asia Sudoriental','🇹🇭','Tailandesa'),
  ('TJ','Tayikistán','TJK','762','Tajikistan','Tadjikistan','República de Tayikistán','+992','Asia Central','🇹🇯','Tayika'),
  ('TK','Tokelau','TKL','772','Tokelau','Tokelau','Tokelau','+690','Oceanía','🇹🇰',NULL),
  ('TL','Timor Oriental','TLS','626','Timor-Leste','Timor oriental','República Democrática de Timor Oriental','+670','Asia Sudoriental','🇹🇱','Timorense'),
  ('TM','Turkmenistán','TKM','795','Turkmenistan','Turkménistan','Turkmenistán','+993','Asia Central','🇹🇲','Turcomana'),
  ('TN','Túnez','TUN','788','Tunisia','Tunisie','República de Túnez','+216','África','🇹🇳','Tunecina'),
  ('TO','Tonga','TON','776','Tonga','Tonga','Reino de Tonga','+676','Oceanía','🇹🇴','Tongana'),
  ('TR','Turquía','TUR','792','Türkiye','Turquie','República de Turquía','+90','Europa','🇹🇷','Turca'),
  ('TT','Trinidad y Tobago','TTO','780','Trinidad and Tobago','Trinité-et-Tobago','República de Trinidad y Tobago','+1-868','El Caribe','🇹🇹','Trinitense'),
  ('TV','Tuvalu','TUV','798','Tuvalu','Tuvalu','Tuvalu','+688','Oceanía','🇹🇻','Tuvaluense'),
  ('TW','Taiwán','TWN','158','Taiwan','Taïwan','Taiwán','+886','Asia Oriental','🇹🇼','Taiwanesa'),
  ('TZ','Tanzania','TZA','834','Tanzania','Tanzanie','República Unida de Tanzania','+255','África','🇹🇿','Tanzana'),
  ('UA','Ucrania','UKR','804','Ukraine','Ukraine','Ucrania','+380','Europa','🇺🇦','Ucraniana'),
  ('UG','Uganda','UGA','800','Uganda','Ouganda','República de Uganda','+256','África','🇺🇬','Ugandesa'),
  ('UM','Islas Ultramarinas Menores de los Estados Unidos','UMI','581','U.S. Minor Outlying Islands','Îles mineures des États-Unis','Islas Ultramarinas Menores de los Estados Unidos','+1','Oceanía','🇺🇲',NULL),
  ('US','Estados Unidos','USA','840','United States','États-Unis','Estados Unidos de América','+1','América del Norte','🇺🇸','Estadounidense'),
  ('UY','Uruguay','URY','858','Uruguay','Uruguay','República Oriental del Uruguay','+598','América del Sur','🇺🇾','Uruguaya'),
  ('UZ','Uzbekistán','UZB','860','Uzbekistan','Ouzbékistan','República de Uzbekistán','+998','Asia Central','🇺🇿','Uzbeka'),
  ('VA','Ciudad del Vaticano','VAT','336','Vatican City','Vatican','Estado de la Ciudad del Vaticano','+379','Europa','🇻🇦','Vaticana'),
  ('VC','San Vicente y las Granadinas','VCT','670','Saint Vincent and the Grenadines','Saint-Vincent-et-les-Grenadines','San Vicente y las Granadinas','+1-784','El Caribe','🇻🇨','Sanvicentina'),
  ('VE','Venezuela','VEN','862','Venezuela','Venezuela','República Bolivariana de Venezuela','+58','América del Sur','🇻🇪','Venezolana'),
  ('VG','Islas Vírgenes Británicas','VGB','092','British Virgin Islands','Îles Vierges britanniques','Islas Vírgenes Británicas','+1-284','El Caribe','🇻🇬',NULL),
  ('VI','Islas Vírgenes de los Estados Unidos','VIR','850','U.S. Virgin Islands','Îles Vierges américaines','Islas Vírgenes de los Estados Unidos','+1-340','El Caribe','🇻🇮',NULL),
  ('VN','Vietnam','VNM','704','Vietnam','Viêt Nam','República Socialista de Vietnam','+84','Asia Sudoriental','🇻🇳','Vietnamita'),
  ('VU','Vanuatu','VUT','548','Vanuatu','Vanuatu','República de Vanuatu','+678','Oceanía','🇻🇺','Vanuatense'),
  ('WF','Wallis y Futuna','WLF','876','Wallis and Futuna','Wallis-et-Futuna','Wallis y Futuna','+681','Oceanía','🇼🇫',NULL),
  ('WS','Samoa','WSM','882','Samoa','Samoa','Estado Independiente de Samoa','+685','Oceanía','🇼🇸','Samoana'),
  ('XK','Kosovo',NULL,NULL,'Kosovo','Kosovo','República de Kosovo','+383','Europa','🇽🇰','Kosovar'),
  ('YE','Yemen','YEM','887','Yemen','Yémen','República de Yemen','+967','Oriente Medio','🇾🇪','Yemení'),
  ('YT','Mayotte','MYT','175','Mayotte','Mayotte','Mayotte','+262','África','🇾🇹','Mayotense'),
  ('ZA','Sudáfrica','ZAF','710','South Africa','Afrique du Sud','República de Sudáfrica','+27','África','🇿🇦','Sudafricana'),
  ('ZM','Zambia','ZMB','894','Zambia','Zambie','República de Zambia','+260','África','🇿🇲','Zambiana'),
  ('ZW','Zimbabue','ZWE','716','Zimbabwe','Zimbabwe','República de Zimbabue','+263','África','🇿🇼','Zimbabuense')
ON CONFLICT (clave_pais) 
DO UPDATE SET 
  nombre_pais        = EXCLUDED.nombre_pais,
  iso_alpha_3       = EXCLUDED.iso_alpha_3,
  iso_numeric       = EXCLUDED.iso_numeric,
  nombre_en         = EXCLUDED.nombre_en,
  nombre_fr         = EXCLUDED.nombre_fr,
  nombre_oficial_es = EXCLUDED.nombre_oficial_es,
  codigo_telefono   = EXCLUDED.codigo_telefono,
  region            = EXCLUDED.region,
  emoji_bandera     = EXCLUDED.emoji_bandera,
  nacionalidad      = EXCLUDED.nacionalidad,
  fecha_modificacion = NOW();

-- 2. ACTUALIZAR ABREVIATURA E ISO 3166-2 PARA LOS 32 ESTADOS DE MÉXICO
UPDATE public.ades_estados AS e SET
  abreviatura = d.abr,
  iso_3166_2  = d.iso2
FROM (VALUES
  ('01','AGS', 'MX-AGU'),
  ('02','BCN', 'MX-BCN'),
  ('03','BCS', 'MX-BCS'),
  ('04','CAM', 'MX-CAM'),
  ('05','COAH','MX-COA'),
  ('06','COL', 'MX-COL'),
  ('07','CHIS','MX-CHP'),
  ('08','CHIH','MX-CHH'),
  ('09','CDMX','MX-CMX'),
  ('10','DGO', 'MX-DUR'),
  ('11','GTO', 'MX-GUA'),
  ('12','GRO', 'MX-GRO'),
  ('13','HGO', 'MX-HID'),
  ('14','JAL', 'MX-JAL'),
  ('15','MEX', 'MX-MEX'),
  ('16','MICH','MX-MIC'),
  ('17','MOR', 'MX-MOR'),
  ('18','NAY', 'MX-NAY'),
  ('19','NL',  'MX-NLE'),
  ('20','OAX', 'MX-OAX'),
  ('21','PUE', 'MX-PUE'),
  ('22','QRO', 'MX-QUE'),
  ('23','QROO','MX-ROO'),
  ('24','SLP', 'MX-SLP'),
  ('25','SIN', 'MX-SIN'),
  ('26','SON', 'MX-SON'),
  ('27','TAB', 'MX-TAB'),
  ('28','TAMPS','MX-TAM'),
  ('29','TLAX','MX-TLA'),
  ('30','VER', 'MX-VER'),
  ('31','YUC', 'MX-YUC'),
  ('32','ZAC', 'MX-ZAC')
) AS d(clave, abr, iso2)
WHERE e.clave_estado = d.clave;

-- 3. ASEGURAR COLUMNAS DE AUDITORÍA EN ADES_USUARIO_ROLES
ALTER TABLE public.ades_usuario_roles 
  ADD COLUMN IF NOT EXISTS fecha_modificacion   TIMESTAMPTZ DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS usuario_modificacion VARCHAR(150) DEFAULT CURRENT_USER;

-- 4. POBLAR LA RELACIÓN DE USUARIOS Y ROLES (ADES_USUARIO_ROLES)
INSERT INTO public.ades_usuario_roles (usuario_id, rol_id, peso)
SELECT id, rol_id, 100 
FROM public.ades_usuarios 
WHERE rol_id IS NOT NULL
ON CONFLICT (usuario_id, rol_id) DO NOTHING;

COMMIT;
